### ISSUE TITLE
Ultimate furnace recipe not working

### ISSUE THREAD

**Issue by HannesNeirynck** [NillerMedDild/Enigmatica2ExpertSkyblock#214] opened 2018-10-29 00:43 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When making the ultimate furnace, the Elite Smelting Factory causes problems because like all mecanism machines it keeps its configs etc after being broken. Because you need to place the machine down to be able to upgrade it (done in-world)

**Modpack version (Do not use "latest")**
1.16a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

![screenshot](https://i.imgur.com/4XLhdIH.jpg)

**Additional context**

Tested in normal crafting table and applied energistics crafting terminal

**Comment by NillerMedDild** [comment] 2018-10-29 06:09
Duplicate of #198

**Closed by NillerMedDild** 2018-10-29 06:09 UTC
