### ISSUE TITLE
Lapis Duplication with the IC2 Compressor

### ISSUE THREAD

**Issue by SuperKael** [NillerMedDild/Enigmatica2ExpertSkyblock#244] opened 2018-12-01 07:40 UTC
**Issue Description**

If you put a piece of lapis into an IC2 Compressor, it becomes a lapis block.

**Modpack version (Do not use "latest")**

Version 1.17

**Additional context**

Presumably, it should take nine lapis per block, not one...

**Comment by NillerMedDild** [comment] 2018-12-01 18:03
Thank you for the report, it has been reported to the mod developer :)
https://bt.industrial-craft.net/view.php?id=2451

**Comment by SuperKael** [comment] 2018-12-01 18:08
That doesn't surprise me, since they are almost entirely the same pack after all.

**Comment by NillerMedDild** [comment] 2018-12-13 08:11
Closed because there's nothing more I can do, it will be fixed by the mod dev.

**Comment by igrvak** [comment] 2020-05-23 06:15
The bug is still not fixed, btw.

**Comment by SuperFurias** [comment] 2020-05-23 17:57
After two years? are we serious?

**Comment by NillerMedDild** [comment] 2020-05-23 18:09
I confirmed this was fixed a long time ago, but I cannot know for sure whether it's still fixed.

**Comment by igrvak** [comment] 2020-05-23 18:28
Hello Niels. I've checked, and the bug is consistently reproducible in the latest version (twitch, modpack version 1.80, Windows 10 x64, Minecraft 1.12.2, Forge 14.23.5.2847).

**Comment by NillerMedDild** [comment] 2020-05-23 19:03
This is not the issue tracker for E2E, this is for skyblock.

**Comment by Blutkirsche** [comment] 2020-05-30 15:53
hi there,
I testet it a moment ago and it doesn't work. the problem IS FIXED in
Enigmatica 2 Expert Skyblock 1.35

**Comment by NillerMedDild** [comment] 2020-05-30 18:01
Would you mind supplying a screenshot as extra proof @Blutkirsche? :)

**Comment by Blutkirsche** [comment] 2020-05-30 20:24
1lapis: 
https://filehorst.de/d/dijjCaCv
9 lapis:
https://filehorst.de/d/djjfroxb
https://filehorst.de/d/dsfFAzHa

**Comment by NillerMedDild** [comment] 2020-05-30 20:28
Errrr... imgur please?

**Comment by Blutkirsche** [comment] 2020-05-31 08:18
i don't wanna use this colorexplosion, sry. i edit the links above.

**Comment by NillerMedDild** [comment] 2020-05-31 08:19
Thank you :)

**Closed by NillerMedDild** 2020-05-31 08:19 UTC
Labels: Type: Bug
