### ISSUE TITLE
[BUG] Lithium-Manganese DiOxide

### ISSUE THREAD

**Issue by SanMan911** [NillerMedDild/Enigmatica2ExpertSkyblock#238] opened 2018-11-22 07:40 UTC
## BUG### 
##Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
According to JEI, 1 Lithium + 1 Manganese Dioxide should give 2 Lithium-Manganese Dioxide Metal (in the Nuclearcraft Alloy Smelter). However, when trying to craft, it gives 2 Magnesium Diborode alloy instead.

**Modpack Version**
1.16a

**Additional Context**
Since JEI asked to make in the Nuclearcraft Alloy smelter, I didn't try the industion smelter or the EnderIO Alloy smelter. I'll post the results when I am able to do.it in the evening.

**Comment by SanMan911** [comment] 2018-11-22 07:46
Just a quick update:
Sorry for the earlier typo.. The Nuclearcraft Alloy Furnace makes the Lithium Manganese Dioxide, but it is the EnderIO Alloy Smelter that is probably not oredicted properly and that gives Magnesium Diboride.

Possible Hotfix:
Disable the EnderIO Alloy Smelter Recipe or Oredict the smelter.

**Comment by NillerMedDild** [comment] 2018-11-22 07:46
Duplicate of #223 - Already fixed on their end :)

**Closed by NillerMedDild** 2018-11-22 07:46 UTC
