### ISSUE TITLE
Intergrated Dynamics Mechanical Drying Basin Uncraftable

### ISSUE THREAD

**Issue by Philenst** [NillerMedDild/Enigmatica2ExpertSkyblock#556] opened 2020-05-10 09:44 UTC
**Modpack version**
Enigmatica 2: Expert Skyblock 1.35 (client and server)

**Issue**
Intergrated Dynamics Mechanical Drying Basin Uncraftable
![image](https://user-images.githubusercontent.com/20720278/81495810-f625f600-92aa-11ea-8605-5573e25b3320.png)
Have tried charged and discharged batteries, also tried a regular crafting table instead of AE2.
It seems this was fixed in Expert but not Expert Skyblock.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment] 2020-05-10 10:43
Duplicate of #555

**Closed** 2020-05-10 10:44 UTC
