### ISSUE TITLE
Advanced rocketry Liquid IO Circuit uncraftable in assembling machine

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2ExpertSkyblock#215] opened 2018-10-29 09:39 UTC
**Issue Description**
The advanced rocketry Liquid IO Circuit still has the Extra Cells 1k fluid storage component in the recipe for the Precision Assembler, instead of the new AE2 version. The regular crafting table recipe uses the AE2 one so it works.

**Modpack version (Do not use "latest")**
1.16a

**Screenshots**
![2018-10-29_20 27 20](https://user-images.githubusercontent.com/2611674/47641651-b90f7c80-dbba-11e8-9ebc-15a6545475d3.png)

**Comment by Rodg88** [comment] 2018-10-29 10:54
The cfg in question is config/advRocketry/PrecisionAssembler.xml
line	88		<itemStack>extracells:storage.component 3 4</itemStack>
replace with <itemStack>appliedenergistics2:material 3 54</itemStack>

**Comment by NillerMedDild** [comment] 2018-10-29 11:43
Duplicate of #214

**Closed by NillerMedDild** 2018-10-29 11:43 UTC
