### ISSUE TITLE
Game crashes when starting game

### ISSUE THREAD

**Issue by StinkyVoet** [NillerMedDild/Enigmatica2ExpertSkyblock#520] opened 2019-08-12 07:47 UTC
**Modpack version**
Version 1.30

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/DLMLWA5b

**Issue**
Game crashes when starting up, I figured out the Applied Energistics block façades and the dummy fluid item base are causing an issue.

**Comment by NillerMedDild** [comment] 2019-08-12 11:28
Have you tried more than once? :) I believe this issue is caused by a rare event where items load out of order.

**Comment by StinkyVoet** [comment] 2019-08-15 10:41
Yes, I have tried multiple times

**Comment by NillerMedDild** [comment] 2019-08-15 10:42
I recommend re-installing in that case.

**Comment by StinkyVoet** [comment] 2019-08-15 10:45
I will try that, thanks. I'll report back if the issue remains

**Comment by NillerMedDild** [comment] 2019-08-15 11:41
Thanks, I'll close the issue for now :)

**Closed by NillerMedDild** 2019-08-15 11:41 UTC
Labels: Type: Invalid
